/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm32l4xx.h"
#include"stm32l4xx_spi_driver.h"
#include<string.h>

void SPI1_GPIOInit(void)
{
	GPIO_Handle_t SPIPin;

	SPIPin.pGPIOx=GPIOA;
	SPIPin.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_ALTFN;
	SPIPin.GPIO_PinConfig.GPIO_PinAltFunMode=5;
	SPIPin.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
	SPIPin.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;
	SPIPin.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;

	//sclk
	SPIPin.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&SPIPin);

	//mosi
	SPIPin.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_7;
	GPIO_Init(&SPIPin);

	//miso
	//SPIPin.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_6;
	//GPIO_Init(&SPIPin);

	//nss
	SPIPin.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_4;
	GPIO_Init(&SPIPin);

}

void SPI1_Init(void)
{
	SPI_Handle_t SPI1Handle;

	SPI1Handle.pSPIx = SPI1;
	SPI1Handle.SPIConfig.SPI_BusConfig=SPI_BUS_CONFIG_FD;
	SPI1Handle.SPIConfig.SPI_DeviceMode=SPI_DEVICE_MODE_MASTER;
	SPI1Handle.SPIConfig.SPI_SclkSpeed=SPI_SCLK_SPEED_DIV8;
	SPI1Handle.SPIConfig.SPI_DFF=SPI_DFF_8BITS;
	SPI1Handle.SPIConfig.SPI_CPOL=SPI_CPOL_LOW;
	SPI1Handle.SPIConfig.SPI_CPHA=SPI_CPHA_LOW;
	SPI1Handle.SPIConfig.SPI_SSM=SPI_SSM_DI;

	SPI_Init(&SPI1Handle);
}
void GPIO_ButtonInit(void)
{
	GPIO_Handle_t GPIOBtn;
	memset(&GPIOBtn,0,sizeof(GPIOBtn));
	GPIOBtn.pGPIOx = GPIOC;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_PeriClockControl(GPIOC,ENABLE);
	GPIO_Init(&GPIOBtn);

}

void delay(void)
{
	for(uint32_t i = 0 ; i < 250000 ; i ++);
}
int main(void)
{
    char data[]="SPI";
    GPIO_ButtonInit();
    SPI1_GPIOInit();
    SPI1_Init();
    while(1)
    {
  //  while((GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13)==1));
    delay();
    SPI_SSOEConfig(SPI1,ENABLE);
    SPI_PeripheralControl(SPI1,ENABLE);
    uint8_t datalen =3;
    SPI_SendData(SPI1,(uint8_t *)&datalen, 1);

    SPI_SendData(SPI1, (uint8_t*)data, 3);

    while(SPI_GetFlagStatus(SPI1,(1<<7)));

    SPI_PeripheralControl(SPI1, DISABLE);

    }

}
