/*The program toggles an LED on pin PA5 each time the button on pin PC13 is pressed, using an external interrupt for detection.
*/

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#include<stdint.h>
#include<string.h>
#include<stdio.h>
#include"stm32l4xx.h"
#include"stm32l4xx_gpio_driver.h"

// Simple delay function
void delay()
{
	for(uint32_t i=0; i<250000; i++);
}

int main(void)
{
    /* Declare handles for LED and Button GPIOs */
	GPIO_Handle_t GpioLed, GpioBtn;

    // Clear the structures
	memset(&GpioLed, 0, sizeof(GpioLed));
	memset(&GpioBtn, 0, sizeof(GpioBtn));

    // --- LED Configuration ---
	GpioLed.pGPIOx = GPIOA;                          // LED connected to Port A
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;  // Pin 5
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;    // Output mode
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST; // Fast speed
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP; // Push-pull output
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU; // Pull-up
	GPIO_PeriClockControl(GPIOA, ENABLE);            // Enable GPIOA clock
	GPIO_Init(&GpioLed);                             // Initialize LED GPIO

    // --- Button Configuration ---
	GpioBtn.pGPIOx = GPIOC;                          // Button connected to Port C
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;  // Pin 13
	GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;   // Falling edge interrupt
	GpioBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;  // Fast speed
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU; // Pull-up
	GPIO_PeriClockControl(GPIOC, ENABLE);            // Enable GPIOC clock
	GPIO_Init(&GpioBtn);                             // Initialize button GPIO

    // Configure NVIC for EXTI line (button interrupt)
	GPIO_PRIORITY_CONFIG(IRQ_NO_EXTI15_10, 15);     // Set interrupt priority
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE); // Enable EXTI interrupt

	while(1); // Infinite loop
}

// Interrupt handler for button press (pins 10 to 15)
void EXTI15_10_IRQHandler(void)
{
	GPIO_IRQHandling(GPIO_PIN_NO_13);               // Clear interrupt flag
	GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);    // Toggle LED
	delay();                                        // Simple debounce delay
}
