/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<string.h>
#include<stdio.h>
#include"stm32l4xx.h"
#include"stm32l4xx_gpio_driver.h"
#include"stm32l4xx_usart_driver.h"
uint8_t msg[50]="Uart transmission\r\n";

USART_Handle_t usart2_handle;
void delay(void)
{
	for(uint32_t i = 0 ; i < 250000 ; i ++);
}
void USART2_Init(void)
{

	usart2_handle.pUSARTx =USART2;
	usart2_handle.USART_Config.USART_Baud=USART_STD_BAUD_115200;
	usart2_handle.USART_Config.USART_HWFlowControl=USART_HW_FLOW_CTRL_NONE;
	usart2_handle.USART_Config.USART_Mode=USART_MODE_TXRX;
	usart2_handle.USART_Config.USART_NoOfStopBits=USART_STOPBITS_1;
	usart2_handle.USART_Config.USART_WordLength=USART_WORDLEN_8BITS;
	usart2_handle.USART_Config.USART_ParityControl=USART_PARITY_DISABLE;
	USART_Init(&usart2_handle);
}


void USART2_GPIOInit(void)
{
	GPIO_Handle_t usart2_gpio;
	memset(&usart2_gpio,0,sizeof(usart2_gpio));
	usart2_gpio.pGPIOx =GPIOA;
	usart2_gpio.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_ALTFN;
	usart2_gpio.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PP;
	usart2_gpio.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_PU;
	usart2_gpio.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
	usart2_gpio.GPIO_PinConfig.GPIO_PinAltFunMode=7;

	usart2_gpio.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_2;
	GPIOA_PCLK_EN();
	GPIO_Init(&usart2_gpio);

	usart2_gpio.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_3;
	GPIO_Init(&usart2_gpio);
}
int main(void)
{
	GPIO_Handle_t GpioLed;
	USART2_GPIOInit();
	USART2_Init();
	USART_PeripheralControl(USART2,ENABLE);
	GpioLed.pGPIOx = GPIOA;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_Init(&GpioLed);
	//GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_5);
	USART_SendData(&usart2_handle, msg,19);
	delay();
	uint8_t c;
	USART_ReceiveData(&usart2_handle, &c, 1);
	if(c== 'a')
	{
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, SET);
		delay();
	}
	USART_SendData(&usart2_handle, &c, 1);
	while(1);
}
